baseURL: https://muhsi.in/
title: Muhsin A
paginate: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

# googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: Muhsin A
  description: "Web developer specialized in javascript"
  keywords: [Blog, Portfolio, Webdeveloper, React, Javascript]
  author: Me
  # author: ["Me", "You"] # multiple authors
  # images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false
  hideFooter: true
  searchHidden: false
  

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "/favicons/favicon.ico"
    favicon16x16: "/favicons/favicon-16x16.png"
    favicon32x32: "/favicons/favicon-32x32.png"
    apple_touch_icon: "/favicons/apple-touch-icon.png"

  label:
    text: "Muhsin A"
    icon: /apple-touch-icon.png
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: true # needs to be explicitly set
    title: "Hey there \U0001F44B"
    subtitle: I'm a web dev specialized in JavaScript.
      I'm just swimming through endless libraries and frameworks of javascript to find something that can
      <a href='https://www.youtube.com/watch?v=B8C5sjjhsso' class='title-link' target='_blank' rel='noopener noreferrer'>make the world a better place</a>
      Besides coding I love videogames, music and drawing.
    imageUrl: "/img/avatar.jpg"
    imageWidth: 120
    imageHeight: 120
    imageTitle: my image

    buttons:
      - name: Say Hello?
        url: "mailto:muhsin7ak@gmail.com"

  # home-info mode
  homeInfoParams:
    Title: "Hey there \U0001F44B"
    Content: I'm a web dev specialized in JavaScript.
      I'm just swimming through endless libraries and frameworks of javascript to find something that can
      <a href='https://www.youtube.com/watch?v=B8C5sjjhsso' class='title-link' target='_blank' rel='noopener noreferrer'>make the world a better place</a>
      Besides coding I love videogames, music and drawing.

  socialIcons:
    - name: "Github"
      url: "https://github.com/muhsin7majeed"

    - name: "LinkedIn"
      url: "https://www.linkedin.com/in/muhsin7majeed/"

    - name: "Instagram"
      url: "https://www.instagram.com/muhsin7majeed/"

  analytics:
    google:
      # SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  # editPost:
  #   URL: "https://github.com/<path_to_repo>/content"
  #   Text: "Suggest Changes" # edit text
  #   appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    - identifier: posts
      name: Posts
      url: /posts/
      weight: 10
    # - identifier: tags
    #   name: tags
    #   url: /tags/
    #   weight: 20
    # - identifier: example
    #   name: example.org
    #   url: https://example.org
    #   weight: 30
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai
